project_id = "ipoeckdsktrkvnyjjcoc"

[functions.github-webhook]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false

[functions.generate-documentation]
verify_jwt = false

[functions.explain-node]
verify_jwt = false
